// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto
#ifndef GRPC_message_2eproto__INCLUDED
#define GRPC_message_2eproto__INCLUDED

#include "message.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace message {

class Hangman final {
 public:
  static constexpr char const* service_full_name() {
    return "message.Hangman";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::message::HangmanRequest, ::message::HangmanResponse>> PlayHangman(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::message::HangmanRequest, ::message::HangmanResponse>>(PlayHangmanRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::message::HangmanRequest, ::message::HangmanResponse>> AsyncPlayHangman(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::message::HangmanRequest, ::message::HangmanResponse>>(AsyncPlayHangmanRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::message::HangmanRequest, ::message::HangmanResponse>> PrepareAsyncPlayHangman(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::message::HangmanRequest, ::message::HangmanResponse>>(PrepareAsyncPlayHangmanRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void PlayHangman(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::message::HangmanRequest,::message::HangmanResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::message::HangmanRequest, ::message::HangmanResponse>* PlayHangmanRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::message::HangmanRequest, ::message::HangmanResponse>* AsyncPlayHangmanRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::message::HangmanRequest, ::message::HangmanResponse>* PrepareAsyncPlayHangmanRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::message::HangmanRequest, ::message::HangmanResponse>> PlayHangman(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::message::HangmanRequest, ::message::HangmanResponse>>(PlayHangmanRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::message::HangmanRequest, ::message::HangmanResponse>> AsyncPlayHangman(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::message::HangmanRequest, ::message::HangmanResponse>>(AsyncPlayHangmanRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::message::HangmanRequest, ::message::HangmanResponse>> PrepareAsyncPlayHangman(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::message::HangmanRequest, ::message::HangmanResponse>>(PrepareAsyncPlayHangmanRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void PlayHangman(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::message::HangmanRequest,::message::HangmanResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::message::HangmanRequest, ::message::HangmanResponse>* PlayHangmanRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::message::HangmanRequest, ::message::HangmanResponse>* AsyncPlayHangmanRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::message::HangmanRequest, ::message::HangmanResponse>* PrepareAsyncPlayHangmanRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PlayHangman_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PlayHangman(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::message::HangmanResponse, ::message::HangmanRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_PlayHangman : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PlayHangman() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PlayHangman() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlayHangman(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::message::HangmanResponse, ::message::HangmanRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlayHangman(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::message::HangmanResponse, ::message::HangmanRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PlayHangman<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_PlayHangman : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PlayHangman() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::message::HangmanRequest, ::message::HangmanResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->PlayHangman(context); }));
    }
    ~WithCallbackMethod_PlayHangman() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlayHangman(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::message::HangmanResponse, ::message::HangmanRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::message::HangmanRequest, ::message::HangmanResponse>* PlayHangman(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_PlayHangman<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PlayHangman : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PlayHangman() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PlayHangman() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlayHangman(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::message::HangmanResponse, ::message::HangmanRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PlayHangman : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PlayHangman() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PlayHangman() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlayHangman(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::message::HangmanResponse, ::message::HangmanRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlayHangman(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PlayHangman : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PlayHangman() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->PlayHangman(context); }));
    }
    ~WithRawCallbackMethod_PlayHangman() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlayHangman(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::message::HangmanResponse, ::message::HangmanRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* PlayHangman(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace message


#endif  // GRPC_message_2eproto__INCLUDED
